<a href="https://colab.research.google.com/github/Gauri-Agrawal838/MachineLearningLab/blob/main/17_01_23_(1_Lab).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5
print(a)

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [3]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
print(b.shape)
print(b[0,0], b[0,1], b[1,0])

(2, 3)
1 2 4


In [5]:
a = np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [6]:
b = np.ones((1,2))
print(b)

[[1. 1.]]


In [7]:
c = np.full((2,2), 7)
print(c)

[[7 7]
 [7 7]]


In [8]:
d = np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]


In [9]:
e = np.random.random((2,2))
print(e)

[[0.495885   0.09123746]
 [0.12559215 0.47029127]]


In [10]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b = a[:2,1:3]
print(b)

[[2 3]
 [6 7]]


In [11]:
print(a[0,1])
b[0,0] = 77
print(a[0,1])

2
77


In [12]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
print(a.shape)
a.resize(4,3)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
