<a href="https://colab.research.google.com/github/Gauri-Agrawal838/MachineLearningLab/blob/main/basicsPython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a=np.array([1,2,3])
print(type(a), a.shape, a[0],a[1],a[2])
a[0]=5
print(a)

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [ ]:
b= np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(b.shape)
print(b[0,0], b[0,1], b[0,2])

(2, 3)
1 2 3


In [ ]:
a=np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [ ]:
a= np.ones((2,1))
print(a)

[[1.]
 [1.]]


In [ ]:
a=np.full((1,2), 4)
print(a)

[[4 4]]


In [ ]:
a=np.eye(2)
print(a)

[[1. 0.]
 [0. 1.]]


In [ ]:
a= np.random.random((2,2))
print(a)

[[0.47741422 0.91842425]
 [0.50781616 0.68730152]]


In [ ]:
a=np.array([[1,2,3,1],[4,5,6,2],[7,8,9,3]])
print(a)

[[1 2 3 1]
 [4 5 6 2]
 [7 8 9 3]]


In [ ]:
b=a[:2, 1:3]
print(b)

[[2 3]
 [5 6]]


In [ ]:
print(a[0,1])
b[0,0]=77
print(a[0,1])

2
77


In [ ]:
c=a.reshape(6,2)
print(c)

[[ 1 77]
 [ 3  1]
 [ 4  5]
 [ 6  2]
 [ 7  8]
 [ 9  3]]
